### PR TITLE
Updating mzLib

### PR DESCRIPTION
**Pull request by acesnik**
Still needs test fixes for Promex and bigger top-down tests

### CODE REVIEW

**Comment by acesnik** [comment]
@lschaffer2 Could you take over from here and inspect the top-down results? You can `git pull upstream NewMzLib` to get this branch, and you can push commits to it.

**Comment by lschaffer2** [comment]
Top-down issue fixed - had to do with N-terminal id name

**Comment by acesnik** [comment]
Expecting this latest one to fail currently, but work after updating mzLib to the newest version with original ID fixes. After updating and checking tests, it might be worth another larger test with the mitochondria data.

**Comment by acesnik** [comment]
^Tested with a local nuget package.

**Comment by acesnik** [comment]
I'll hand it back over to you, @lschaffer2

**Comment by lschaffer2** [comment]
Looks good mzlib just needed another update. I'm running through my mito data and if that looks good we can merge today

**Comment by lschaffer2** [comment]
ET still has issues with time. I killed a search after ~25 minutes that took 5 minutes on the old build. Will look into it

**Comment by acesnik** [comment]
Everything looks normal for the full NeuCode run from the ProteoformSuite paper. It finishes in 6.5 mins. Must be a top-down integration issue inside the identification code.

**Comment by acesnik** [comment]
Qualitatively, the quantitative data looks very similar! 😄 
capture

**Comment by lschaffer2** [comment]
The issue was the change in .Equals method in mzlib for modification which is used many times in ET for when we do the dictionary lookup. Putting in changes now

**Comment by acesnik** [comment]
Maybe we should check the hash before using the equal method, since that should be faster.

**Comment by acesnik** [comment]
I think they both use the `Modification.ToString()` method as the foundation, though, so it might not be much faster.

**Comment by lschaffer2** [comment]
Yes they do that was the issue. I made a PR to mzlib which fixed it so it's fast again... I'll push commits in a moment just looking into last differences but results mostly match my old mito results #'s

**Pull request merged**
